### ISSUE TITLE
Rblpapi build issue

### ISSUE THREAD

**Issue by tcrbc** [Rblp/Rblpapi#166]
when building on Redhat Enterprise Linux 6.7 using R version 3.2.4, i'm encountering this error

```
> install.packages("Rblpapi", dep=TRUE)
also installing the dependency “fts”

trying URL 'http://cran.mtu.edu/src/contrib/fts_0.9.9.tar.gz'
Content type 'application/x-gzip' length 49441 bytes (48 KB)
==================================================
downloaded 48 KB

trying URL 'http://cran.mtu.edu/src/contrib/Rblpapi_0.3.3.tar.gz'
Content type 'application/x-gzip' length 156872 bytes (153 KB)
==================================================
downloaded 153 KB

* installing *source* package “fts” ...
** package “fts” successfully unpacked and MD5 sums checked
** libs
g++ -I/usr/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include -I"/data1/R-3.2.4/lib64/R/library/BH/include"  -I./tslib -I./helpers -fpic  -g -O2  -c diff.cpp -o diff.o
g++ -I/usr/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include -I"/data1/R-3.2.4/lib64/R/library/BH/include"  -I./tslib -I./helpers -fpic  -g -O2  -c interface.cpp -o interface.o
g++ -I/usr/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include -I"/data1/R-3.2.4/lib64/R/library/BH/include"  -I./tslib -I./helpers -fpic  -g -O2  -c lag.cpp -o lag.o
g++ -I/usr/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include -I"/data1/R-3.2.4/lib64/R/library/BH/include"  -I./tslib -I./helpers -fpic  -g -O2  -c lead.cpp -o lead.o
g++ -I/usr/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include -I"/data1/R-3.2.4/lib64/R/library/BH/include"  -I./tslib -I./helpers -fpic  -g -O2  -c pad.cpp -o pad.o
g++ -shared -L/usr/local/R-3.2.4/lib64/R/lib -L/usr/local/lib64 -o fts.so diff.o interface.o lag.o lead.o pad.o -L/usr/local/R-3.2.4/lib64/R/lib -lR
installing to /data1/R-3.2.4/lib64/R/library/fts/libs
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (fts)
* installing *source* package “Rblpapi” ...
** package “Rblpapi” successfully unpacked and MD5 sums checked
Setting up compilation for a linux 64-bit system
** libs
g++ -std=c++0x -I/usr/local/R-3.2.4/lib64/R/include -DNDEBUG -I../inst/include/ -I. -I/usr/local/include -I"/data1/R-3.2.4/lib64/R/library/Rcpp/include" -I"/data1/R-3.2.4/lib64/R/library/BH/include"   -fpic  -g -O2 -c RcppExports.cpp -o RcppExports.o
g++ -std=c++0x -I/usr/local/R-3.2.4/lib64/R/include -DNDEBUG -I../inst/include/ -I. -I/usr/local/include -I"/data1/R-3.2.4/lib64/R/library/Rcpp/include" -I"/data1/R-3.2.4/lib64/R/library/BH/include"   -fpic  -g -O2 -c authenticate.cpp -o authenticate.o
g++ -std=c++0x -I/usr/local/R-3.2.4/lib64/R/include -DNDEBUG -I../inst/include/ -I. -I/usr/local/include -I"/data1/R-3.2.4/lib64/R/library/Rcpp/include" -I"/data1/R-3.2.4/lib64/R/library/BH/include"   -fpic  -g -O2 -c bdh.cpp -o bdh.o
bdh.cpp: In function “Rcpp::List bdh_Impl(SEXPREC*, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::string, SEXPREC*, SEXPREC*, SEXPREC*, bool, SEXPREC*)”:
bdh.cpp:108: error: expected initializer before “:” token
bdh.cpp:112: error: could not convert ârdsrvâ to “bool”
bdh.cpp:113: error: expected primary-expression before “if”
bdh.cpp:113: error: expected “)” before “if”
bdh.cpp:117: error: “rdsrv” was not declared in this scope
make: *** [bdh.o] Error 1
ERROR: compilation failed for package “Rblpapi”
* removing “/data1/R-3.2.4/lib64/R/library/Rblpapi”

The downloaded source packages are in
        “/tmp/RtmpMisnMT/downloaded_packages”
Warning message:
In install.packages("Rblpapi", dep = TRUE) :
  installation of package “Rblpapi” had non-zero exit status
>
```

**Comment by eddelbuettel** [comment]
Most likely a compiler issue.  When R was built noticed that C++11 support was partial: `g++ -std=c++0x`.

What `g++` version do you have, and could you upgrade (or, alternatively, have someone look into what it would take to adjust the code).  That line is just

```C++
    for(auto f : fldinfos) {
        rtypes.push_back(fieldInfoToRblpapiT(f.datatype,f.ftype));
    }
```

and that was most @armstrtw being fancy :)    We could probably write this in more conservative C++ as we don't really use fancy C++11.

Then again, our code _does_ build on `g++-4.6.*` as used for Windows builds of CRAN, and if you or RHEL insist on `g++-4.4.*` ... then it is not really fair to expect us to cope with it.

But pull requests would be fine.

**Comment by tcrbc** [comment]
the g++ version i'm using the RHEL 6 stock version

gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC)

**Comment by eddelbuettel** [comment]
Any chance you could complement this with a more modern variant?  `g++-4.6` or later?

**Comment by tcrbc** [comment]
i used gcc version 4.9.2 instead of the stock version, and that got through the build, thank you!

**Comment by eddelbuettel** [comment]
Excellent.  I will make a note in the [DESCRIPTION](https://github.com/Rblp/Rblpapi/blob/master/DESCRIPTION) file that we do in fact need a full-blown more recent compiler.

**Comment by eddelbuettel** [comment]
Done in 92a6de9
